name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
        working-directory: my-app

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install   # ✅ ADD THIS
        working-directory: my-app
      - run: npm run build
        working-directory: my-app

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install   # ✅ ADD THIS
        working-directory: my-app
      - run: npm run lint
        working-directory: my-app

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install   # ✅ ADD THIS
        working-directory: my-app
      - run: npm test
        working-directory: my-app